quarkus:
  http:
    port: 3001
  datasource:
    db-kind: h2
    username: sa
    password: sa
    jdbc:
      url: jdbc:h2:mem:social_db
      max-size: 16

  hibernate-orm:
    database:
      generation: drop-and-create
    log:
      sql: true