quarkus:
  http:
    port: 3000
  datasource:
    db-kind: postgresql
    username: social_srv
    password: s0c14l+s3rv1c3
    jdbc:
      url: jdbc:postgresql://localhost:5432/social_db
      max-size: 16
  swagger-ui:
    always-include: true
    path: /swagger
    theme: outline
  smallrye-openapi:
    path: /openapi
    info-title: Quarkus Social API Doc
    info-version: 1.0.0
    info-description: Quarkus social is an API to practice JAVA with Quarkus